@echo off
echo Starting Flutter Web (CORS disabled for dev)...
flutter run -d chrome --web-hostname 0.0.0.0 --web-port 53568 --web-browser-flag "--disable-web-security" --web-browser-flag "--user-data-dir=C:\tmp\flutter_chrome_dev"
